# Accuracy of IDF evacuation orders in Gaza

In [ ]:
!pip install deep-translator langchain langchain-google-genai

Requirement already satisfied: deep-translator in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (1.11.4)
Requirement already satisfied: langchain in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (0.3.25)
Requirement already satisfied: langchain-google-genai in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (2.1.4)
Requirement already satisfied: mordecai in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (2.1.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from deep-translator) (4.13.4)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from deep-translator) (2.32.3)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.58 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (0.3.62)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (0.3.8)
Requirement already satisfied: langsmith<0.4,>=0.1.17 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (0.3.42)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (2.11.5)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (2.0.41)
Requirement already satisfied: PyYAML>=5.3 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain) (6.0.2)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-ai-generativelanguage<0.7.0,>=0.6.18 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain-google-genai) (0.6.18)
Requirement already satisfied: editdistance>=0.5.3 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (0.8.1)
Requirement already satisfied: elasticsearch==5.4.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (5.4.0)
Requirement already satisfied: elasticsearch-dsl==5.3.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (5.3.0)
Requirement already satisfied: h5py>=2.10.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (3.13.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (2.2.3)
Requirement already satisfied: spacy<3.0,>=2.3 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (2.3.9)
Requirement already satisfied: tensorflow>=2.2.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (2.19.0)
Requirement already satisfied: tqdm>=4.28.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (4.67.1)
Requirement already satisfied: numpy>=1.12 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from mordecai) (2.1.3)
Requirement already satisfied: urllib3<2.0,>=1.8 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from elasticsearch==5.4.0->mordecai) (1.26.20)
Requirement already satisfied: six in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from elasticsearch-dsl==5.3.0->mordecai) (1.17.0)
Requirement already satisfied: python-dateutil in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from elasticsearch-dsl==5.3.0->mordecai) (2.9.0.post0)
Requirement already satisfied: soupsieve>1.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.13.2)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (2.24.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (2.40.2)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (5.29.4)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain-core<1.0.0,>=0.3.58->langchain) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain-core<1.0.0,>=0.3.58->langchain) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langchain-core<1.0.0,>=0.3.58->langchain) (24.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langsmith<0.4,>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langsmith<0.4,>=0.1.17->langchain) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langsmith<0.4,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from langsmith<0.4,>=0.1.17->langchain) (0.23.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pandas>=0.24.2->mordecai) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pandas>=0.24.2->mordecai) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.4.26)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (3.0.10)
Requirement already satisfied: thinc<7.5.0,>=7.4.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (7.4.6)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (0.7.11)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (0.10.1)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (1.0.7)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (1.0.2)
Requirement already satisfied: setuptools in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (65.5.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from spacy<3.0,>=2.3->mordecai) (1.1.3)
Requirement already satisfied: greenlet>=1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.2)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (2.3.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (3.4.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (3.1.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (1.71.0)
Requirement already satisfied: tensorboard~=2.19.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (3.10.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (0.5.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorflow>=2.2.0->mordecai) (0.31.0)
Requirement already satisfied: colorama in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tqdm>=4.28.1->mordecai) (0.4.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow>=2.2.0->mordecai) (0.45.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (1.70.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (1.71.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (4.9.1)
Requirement already satisfied: anyio in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.58->langchain) (3.0.0)
Requirement already satisfied: rich in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from keras>=3.5.0->tensorflow>=2.2.0->mordecai) (14.0.0)
Requirement already satisfied: namex in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from keras>=3.5.0->tensorflow>=2.2.0->mordecai) (0.1.0)
Requirement already satisfied: optree in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from keras>=3.5.0->tensorflow>=2.2.0->mordecai) (0.16.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorboard~=2.19.0->tensorflow>=2.2.0->mordecai) (3.8)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorboard~=2.19.0->tensorflow>=2.2.0->mordecai) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from tensorboard~=2.19.0->tensorflow>=2.2.0->mordecai) (3.1.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-ai-generativelanguage<0.7.0,>=0.6.18->langchain-google-genai) (0.6.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow>=2.2.0->mordecai) (3.0.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from rich->keras>=3.5.0->tensorflow>=2.2.0->mordecai) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from rich->keras>=3.5.0->tensorflow>=2.2.0->mordecai) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\gizem\onedrive\school\werk\volkskrant\gaza-evacuatieorders\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow>=2.2.0->mordecai) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "c:\Users\Gizem\OneDrive\School\Werk\volkskrant\gaza-evacuatieorders\venv\Lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "c:\Users\Gizem\OneDrive\School\Werk\volkskrant\gaza-evacuatieorders\venv\Lib\site-packages\thinc\neural\__init__.py", line 4, in <module>
    from ._classes.model import Model  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Gizem\OneDrive\School\Werk\volkskrant\gaza-evacuatieorders\venv\Lib\site-packages\thinc\neural\_classes\model.py", line 11, in <module>
    from ..train import Trainer
  File "c:\Users\Gizem\OneDrive\School\Werk\volkskrant\gaza-evacuatieorders\venv\Lib\site-packages\thinc\neural\train.py", line 7, in <module>
    from .optimizers import Adam, linear_decay
  File "thinc\neural\optimizers.pyx", line 14, in init thinc.neural.optimizers
  File "thinc\neural\ops.pyx", line 1, in init thinc.neural.ops
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

5.5.2: Pulling from library/elasticsearch
219d2e45b4af: Pulling fs layer
f478c95dec23: Pulling fs layer
017932737cd4: Pulling fs layer
28b38dddf546: Pulling fs layer
980edaaff53b: Pulling fs layer
9a2de73c3385: Pulling fs layer
98d9d4b54ad0: Pulling fs layer
f822bfcfdea9: Pulling fs layer
b08144fb654d: Pulling fs layer
5f9ae4a86d71: Pulling fs layer
288ffe538f2f: Pulling fs layer
47b728c174e9: Pulling fs layer
14ed224fb73f: Pulling fs layer
a482fbcfe407: Pulling fs layer
92aff82bd83f: Pulling fs layer
f478c95dec23: Download complete
28b38dddf546: Download complete
98d9d4b54ad0: Download complete
47b728c174e9: Download complete
b08144fb654d: Download complete
9a2de73c3385: Download complete
288ffe538f2f: Download complete
017932737cd4: Download complete
5f9ae4a86d71: Download complete
14ed224fb73f: Download complete
980edaaff53b: Download complete
a482fbcfe407: Download complete
f822bfcfdea9: Download complete
219d2e45b4af: Download complete
219d2e45b4af: Pull complete
a482fbcfe407: Pull complete
980edaaff53b: Pull complete
288ffe538f2f: Pull complete
017932737cd4: Pull complete
28b38dddf546: Pull complete
92aff82bd83f: Download complete
b08144fb654d: Pull complete
14ed224fb73f: Pull complete
92aff82bd83f: Pull complete
f478c95dec23: Pull complete
5f9ae4a86d71: Pull complete
98d9d4b54ad0: Pull complete
47b728c174e9: Pull complete
9a2de73c3385: Pull complete
f822bfcfdea9: Pull complete
Digest: sha256:3686a5757ed46c9dbcf00f6f71fce48ffc5413b193a80d1c46a21e7aad4c53ad
Status: Downloaded newer image for elasticsearch:5.5.2
docker.io/library/elasticsearch:5.5.2

'wget' is not recognized as an internal or external command,
operable program or batch file.
tar: Error opening archive: Failed to open 'geonames_index.tar.gz'
docker: Error response from daemon: create $(pwd)/geonames_index: "$(pwd)/geonames_index" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

Run 'docker run --help' for more information

In [ ]:
# Install dependencies
import os
import time
import asyncio
from dotenv import load_dotenv
import re
import pandas as pd
from deep_translator import GoogleTranslator
from datetime import datetime, timedelta
from langchain_google_genai import GoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain.chains import LLMChain

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

## 1. Displacements

The [Gaza Maps](https://gazamaps.com/) project maintains a database of all known IDF evacuation orders issued on official IDF Arabic channels, or via leaflets in Gaza.

In [41]:
# Load the displacement data
displacement = pd.read_csv("data/displacement_updated.csv")
displacement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     109 non-null    object
 1   x_source                 93 non-null     object
 2   x_text                   93 non-null     object
 3   x_text_translated        93 non-null     object
 4   x_timestamp_utc3         93 non-null     object
 5   evacuation_zone_prompt   109 non-null    object
 6   facebook_source          21 non-null     object
 7   facebook_timestamp_utc3  21 non-null     object
 8   leaflet                  19 non-null     object
 9   leaflet_text_translated  18 non-null     object
 10  safezone_prompt          109 non-null    object
 11  link                     95 non-null     object
 12  map_idf                  95 non-null     object
 13  map_full                 79 non-null     object
 14  map_zoom                 79 non-null     object
 15  displacement_blocks      85 non-null     object
 16  labeled_safe_blocks      31 non-null     object
 17  evacuation_zone          109 non-null    object
 18  safezone                 109 non-null    object
 19  area_sq_km_displacement  95 non-null     float64
 20  area_sq_km_labeled_safe  95 non-null     float64
dtypes: float64(2), object(19)
memory usage: 18.0+ KB

### Data cleaning
1. Remove the URL at the end of every tweet in the column `x_text`.
2. Translate every tweet from Arabic to English, creating a new column `x_text_translated`.
3. Convert the column `x_timestamp` to UTC+3, which is the timezone in Gaza.

In [42]:
def remove_urls(text):
    """Remove all URLs from the text."""
    if pd.isna(text) or not isinstance(text, str):
        return text # Leave non-string types unchanged
    return re.sub(r'https://\S+', '', text).strip()
    

def arabic_to_english(text):
    """Translate Arabic text to English."""
    if pd.isna(text) or not isinstance(text, str):
        return text
    try:
        return GoogleTranslator(source='ar', target='en').translate(text)
    except Exception as e:
        print(f"Error translating text: {text} - {e}")
        return text


def convert_date(time_str):
    """Convert a Twitter-style timestamp to hour:minute in UTC+3."""
    if pd.isna(time_str) or not isinstance(time_str, str):
        return time_str
    try:
        # Parse the original UTC datetime string
        dt = datetime.strptime(time_str, "%a %b %d %H:%M:%S %z %Y")     
        # Add 3 hours to get UTC+3
        dt_utc3 = dt + timedelta(hours=3)       
        # Format hour and minute
        time_formatted = dt_utc3.strftime("%H:%M")
        return time_formatted
    except Exception as e:
        print(f"Skipping malformed timestamp '{time_str}': {e}")
        return time_str

In [43]:
# Remove URLs from the tweet text
displacement['x_text'] = displacement['x_text'].apply(remove_urls)

# Translate Arabic tweets to English
# displacement['x_text_translated'] = displacement['x_text'].apply(arabic_to_english)

# Convert the timestamp to UTC+3 hour:minute format
# displacement['x_timestamp_utc3'] = displacement['x_timestamp'].apply(convert_date)

# Remove useless columns
displacement = displacement.drop(['evacuation_zone_prompt', 'safezone_prompt', 'map_full', 'map_zoom'], axis=1)

displacement.head()

,date,x_source,x_text,x_text_translated,x_timestamp_utc3,facebook_source,facebook_timestamp_utc3,leaflet,leaflet_text_translated,link,map_idf,displacement_blocks,labeled_safe_blocks,evacuation_zone,safezone,area_sq_km_displacement,area_sq_km_labeled_safe
0,2025-05-26,https://x.com/AvichayAdraee/status/19269564320...,#عاجل ‼️ الى سكان محافظة خانيونس، بني سهيلا، ع...,"To the residents of Khan Yunis, Bani Suhaila, ...",13:59,https://www.facebook.com/IDFarabicAvichayAdrae...,14:03,NaN,NaN,https://gazamaps.com/displacement/103,https://gazamaps.com/storage/displacement-maps...,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,...",NaN,"Khan Yunis, Bani Suhaila, Abasan, Al-Qarara Go...",Al-Mawasi,154.44,0.0
1,2025-05-21,https://x.com/AvichayAdraee/status/19252451965...,#عاجل ‼️ تحذير خطير الى كل سكان قطاع غزة المتو...,A serious warning to all residents of the Gaza...,20:39,https://www.facebook.com/IDFarabicAvichayAdrae...,20:41,NaN,NaN,https://gazamaps.com/displacement/101,https://gazamaps.com/storage/displacement-maps...,"961, 962, 963, 964, 965, 966, 967, 968, 969, 9...",NaN,"Gaza Strip, Ghaban, Al-Shimaa, Fadous, Al-Mans...",south,13.26,0.0
2,2025-05-19,https://x.com/AvichayAdraee/status/19243953249...,#عاجل ‼️ الى سكان محافظة خان يونس، بني سهيلا و...,"To the residents of Khan Yunis, Bani Suhaila a...",12:22,https://www.facebook.com/IDFarabicAvichayAdrae...,12:23,NaN,NaN,https://gazamaps.com/displacement/100,https://gazamaps.com/storage/displacement-maps...,"36, 37.1, 37.2, 38, 39, 40, 41, 42.1, 42.2, 42...",NaN,"Khan Yunis, Bani Suhaila, Abasan",Mawasi area,81.24,0.0
3,2025-05-18,https://x.com/avichayadraee/status/19241385814...,#عاجل ‼️ إلى جميع سكان قطاع غزة المتواجدين في...,To all residents of the Gaza Strip located in ...,19:22,https://www.facebook.com/IDFarabicAvichayAdrae...,19:23,NaN,NaN,https://gazamaps.com/displacement/99,https://gazamaps.com/storage/displacement-maps...,"126, 127, 129.1, 129.2, 130.1, 130.2, 131.1, 2...",NaN,"Gaza Strip, Al-Qarara, Salqa, southern Deir al...",Al Mawasi,5.71,0.0
4,2025-05-16,NaN,NaN,NaN,NaN,NaN,NaN,https://idfleaflets.com/53,URGENT WARNING:\n\nTo all those who are in thi...,NaN,NaN,NaN,NaN,Unknown,Unknown,NaN,NaN

The tweet text `x_text_translated` contains the names of the locations designated to be evacuated, and the locations where residents should find shelter. We will use an LLM to extract these locations and put them in separate columns for further analysis.

> Note: Method currently not working. We used the SheetGPT extension for Google Sheets instead with the same prompts.

In [ ]:
try:
    # Load Google Gemini API key
    dotenv_path = os.path.abspath(os.path.join(os.getcwd(), '..', '.env'))
    load_dotenv(dotenv_path)

    google_api_key = os.getenv("GOOGLE_API_KEY")
except:
    google_api_key = input("Your Google API key: ")

# Set up the LLM
llm = GoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=google_api_key)

# Global delay tracker
last_call_time = 0

async def throttled_llm_run(chain, input_data, delay=4):
    """Run LLM chain with rate limit delay (default: 4 seconds)."""
    global last_call_time

    now = time.time()
    time_since_last = now - last_call_time

    if time_since_last < delay:
        await asyncio.sleep(delay - time_since_last)
    
    try:
        result = chain.run(x_text_translated=input_data).strip()
        last_call_time = time.time()  # Update the last call time
        return result
    except Exception as e:
        print(f"Error running LLM chain: {e}")
        return None

In [ ]:
async def extract_evacuations(row):
    """Function to extract the names of locations designated to be evacuated from a tweet."""
    prompt = PromptTemplate.from_template("""
    You will be given a tweet containing an evacuation order to people in specific locations.
    Name the affected locations (not the block numbers, if present in the tweet) where people are ordered to evacuate from, separated by commas.
    If the location names where people should evacuate from are not mentioned in the tweet, answer "Unknown".
    Do not include the area which people are ordered to evacuate to.
                                          
    Tweet: {x_text_translated}
    """)

    chain = LLMChain(llm=llm, prompt=prompt)

    if isinstance(row['x_text_translated'], str):
        # Prompt the LLM to extract evacuation locations
        return await throttled_llm_run(chain, row['x_text_translated'])
    return None


async def extract_safezones(row):
    """Function to extract the names of safe zones from a tweet."""
    prompt = PromptTemplate.from_template("""
    You will be given a tweet containing an evacuation order to people in specific locations.
    Name the safe zones (not the block numbers, if present in the tweet) where people are ordered to evacuate to, separated by commas.
    If the safe zones where people should evacuate to are not mentioned in the tweet, answer "Unknown".
    Do not include the area which people are ordered to evacuate from.
                                          
    Tweet: {x_text_translated}
    """)

    chain = LLMChain(llm=llm, prompt=prompt)

    if isinstance(row['x_text_translated'], str):
        # Prompt the LLM to extract safe zone locations
        return await throttled_llm_run(chain, row['x_text_translated'])
    return None

In [ ]:
# Extract evacuation locations from the translated tweets
# displacement["locations"] = displacement.apply(extract_evacuations, axis=1)

# Extract safe zones from the translated tweets
# displacement["safezones"] = displacement.apply(extract_safezones, axis=1)

## 2. Political violence events

ACLED's [Gaza Monitor](https://acleddata.com/gaza-monitor/#1738833681742-00591c0f-83dc) contains a map and accompanying dataset of all political violence events, demonstration events, and strategic developments recorded in Israel and Palestine started from 7 October 2023.

In [44]:
# Load the ACLED data
acled = pd.read_csv("data/acled_may23.csv")
acled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90242 entries, 0 to 90241
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id_cnty       90242 non-null  object
 1   event_date          90242 non-null  object
 2   year                90242 non-null  int64
 3   time_precision      90242 non-null  int64
 4   disorder_type       90242 non-null  object
 5   event_type          90242 non-null  object
 6   sub_event_type      90242 non-null  object
 7   actor1              90242 non-null  object
 8   assoc_actor_1       20743 non-null  object
 9   inter1              90242 non-null  object
 10  actor2              66166 non-null  object
 11  assoc_actor_2       16778 non-null  object
 12  inter2              66166 non-null  object
 13  interaction         90242 non-null  object
 14  civilian_targeting  21230 non-null  object
 15  iso                 90242 non-null  int64
 16  region              90242 non-null  object
 17  country             90242 non-null  object
 18  admin1              90176 non-null  object
 19  admin2              90129 non-null  object
 20  admin3              17160 non-null  object
 21  location            90242 non-null  object
 22  latitude            90242 non-null  float64
 23  longitude           90242 non-null  float64
 24  geo_precision       90242 non-null  int64
 25  source              90242 non-null  object
 26  source_scale        90242 non-null  object
 27  notes               90242 non-null  object
 28  fatalities          90242 non-null  int64
 29  tags                39009 non-null  object
 30  timestamp           90242 non-null  int64
dtypes: float64(2), int64(6), object(23)
memory usage: 21.3+ MB

### Data cleaning

The [ACLED Codebook](https://acleddata.com/acleddatanew/wp-content/uploads/dlm_uploads/2024/10/ACLED-Codebook-2024-7-Oct.-2024.pdf) contains more information about how ACLED codes and catagorizes data. Based on this we will filter the dataset to only include battles, explosions/remote violence and violence against civilians by the IDF in Gaza after 7 October 2023:

1. Only include dates in the column `event_date` after 2023-10-07.
2. Only include datapoints for 'Political violence' in the column `disorder_type`. Only include the following subcategories within the column `event_type`:
    - Battles
    - Explosions/Remote violence
    - Violence against civilians
3. Only include datapoints that contain 'Military Forces of Israel' in the column `actor1`.
4. Only include datapoints for the location 'Gaza Strip' in the column `admin1`.

In [45]:
# Ensure event_date is in datetime format
acled["event_date"] = pd.to_datetime(acled["event_date"], errors='coerce')

# Filter events types
event_types = ["Battles", "Explosions/Remote violence", "Violence against civilians"]

# Apply filters
acled_filtered = acled[
    (acled["event_date"] > pd.Timestamp("2023-10-07")) &
    (acled["disorder_type"] == "Political violence") &
    (acled["event_type"].isin(event_types)) &
    (acled["actor1"].str.contains("Military Forces of Israel", na=False)) &
    (acled["admin1"] == "Gaza Strip")
]

acled_filtered.head()

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp
4,PSE74167,2025-05-23,2025,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),NaN,External/Other forces,...,Jabalya,31.5272,34.4835,2,Newpress; Palestine News and Information Agenc...,New media-National,"On 23 May 2025, Israeli warplanes targeted a g...",3,NaN,1748304023
5,PSE74182,2025-05-23,2025,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),NaN,External/Other forces,...,Gaza - Southern Remal,31.5168,34.4355,2,Quds News Network,National,"On 23 May 2025, Israeli warplanes targeted sev...",0,NaN,1748304023
6,PSE74194,2025-05-23,2025,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),NaN,External/Other forces,...,An Nusayrat,31.4486,34.3925,1,Palestine News and Information Agency; Quds Ne...,National,"On 23 May 2025, Israeli warplanes targeted the...",3,NaN,1748304023
7,PSE74204,2025-05-23,2025,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),NaN,External/Other forces,...,Abasan al Jadidah,31.3416,34.3459,1,Quds News Network,National,"On 23 May 2025, Israeli warplanes targeted a h...",14,NaN,1748304023
8,PSE74213,2025-05-23,2025,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Israel (2022-),NaN,External/Other forces,...,Al Qararah,31.3739,34.3409,2,Palestine News and Information Agency; Quds Ne...,National,"On 23 May 2025, Israeli helicopters fired live...",1,NaN,1748304024

## 3. Merging the data